----Procedimientos----
-- 1. Buscar producto por nombre
CREATE OR REPLACE PROCEDURE BUSCAR_PRODUCTO_POR_NOMBRE(
    P_NOMBRE IN VARCHAR2
) AS
BEGIN
    FOR R IN (
        SELECT * FROM PRODUCTO
        WHERE UPPER(NOMBRE) LIKE '%' || UPPER(P_NOMBRE) || '%'
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || R.ID_PRODUCTO || ' - ' || R.NOMBRE || ' - $' || R.PRECIO);
    END LOOP;
END;
/

-- 2. Filtrar pedidos por fecha
CREATE OR REPLACE PROCEDURE FILTRAR_PEDIDOS_POR_FECHA(
    P_FECHA_INICIO IN DATE,
    P_FECHA_FIN IN DATE
) AS
BEGIN
    FOR R IN (
        SELECT * FROM PEDIDO
        WHERE FECHA_PEDIDO BETWEEN P_FECHA_INICIO AND P_FECHA_FIN
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('ID PEDIDO: ' || R.ID_PEDIDO || ' - FECHA: ' || R.FECHA_PEDIDO);
    END LOOP;
END;
/

-- 3. Actualizar estado pedido
CREATE OR REPLACE PROCEDURE ACTUALIZAR_ESTADO_PEDIDO(
    P_ID_PEDIDO IN NUMBER,
    P_ESTADO IN VARCHAR2
) AS
BEGIN
    UPDATE PEDIDO
    SET ESTADO = P_ESTADO
    WHERE ID_PEDIDO = P_ID_PEDIDO;

    COMMIT;
END;
/
----Funciones----
-- 1. Calcular IVA (13%)
CREATE OR REPLACE FUNCTION CALCULAR_IVA(
    P_MONTO NUMBER
) RETURN NUMBER IS
BEGIN
    RETURN P_MONTO * 0.13;
END;
/

-- 2. Obtener precio producto
CREATE OR REPLACE FUNCTION OBTENER_PRECIO_PRODUCTO(
    P_ID_PRODUCTO NUMBER
) RETURN NUMBER IS
    V_PRECIO NUMBER;
BEGIN
    SELECT PRECIO INTO V_PRECIO
    FROM PRODUCTO
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;
    RETURN V_PRECIO;
END;
/

-- 3. Calcular stock disponible
CREATE OR REPLACE FUNCTION CALCULAR_STOCK_DISPONIBLE(
    P_ID_PRODUCTO NUMBER
) RETURN NUMBER IS
    V_STOCK NUMBER;
BEGIN
    SELECT STOCK_ACTUAL INTO V_STOCK
    FROM PRODUCTO
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;
    RETURN V_STOCK;
END;
/

-- 4. Formatear nombre cliente
CREATE OR REPLACE FUNCTION FORMATEAR_NOMBRE_CLIENTE(
    P_ID_CLIENTE NUMBER
) RETURN VARCHAR2 IS
    V_NOMBRE VARCHAR2(200);
BEGIN
    SELECT INITCAP(NOMBRE) INTO V_NOMBRE
    FROM CLIENTE
    WHERE ID_CLIENTE = P_ID_CLIENTE;
    RETURN V_NOMBRE;
END;
/

-- 5. Calcular descuento (10%)
CREATE OR REPLACE FUNCTION CALCULAR_DESCUENTO(
    P_MONTO NUMBER
) RETURN NUMBER IS
BEGIN
    RETURN P_MONTO * 0.10;
END;
/

-- 6. Obtener categoría producto
CREATE OR REPLACE FUNCTION OBTENER_CATEGORIA_PRODUCTO(
    P_ID_PRODUCTO NUMBER
) RETURN VARCHAR2 IS
    V_NOMBRE VARCHAR2(50);
BEGIN
    SELECT C.NOMBRE INTO V_NOMBRE
    FROM PRODUCTO P
    JOIN CATEGORIA C ON P.ID_CATEGORIA = C.ID_CATEGORIA
    WHERE P.ID_PRODUCTO = P_ID_PRODUCTO;
    RETURN V_NOMBRE;
END;
/

-- 7. Calcular monto movimiento
CREATE OR REPLACE FUNCTION CALCULAR_MONTO_MOVIMIENTO(
    P_ID_MOVIMIENTO NUMBER
) RETURN NUMBER IS
    V_MONTO NUMBER;
BEGIN
    SELECT CANTIDAD * PRECIO INTO V_MONTO
    FROM MOVIMIENTOS M
    JOIN PRODUCTO P ON M.ID_PRODUCTO = P.ID_PRODUCTO
    WHERE ID_MOVIMIENTO = P_ID_MOVIMIENTO;
    RETURN V_MONTO;
END;
/

-- 8. Calcular días de entrega
CREATE OR REPLACE FUNCTION CALCULAR_DIAS_ENTREGA(
    P_ID_PEDIDO NUMBER
) RETURN NUMBER IS
    V_DIAS NUMBER;
BEGIN
    SELECT FECHA_ENTREGA - FECHA_PEDIDO INTO V_DIAS
    FROM PEDIDO
    WHERE ID_PEDIDO = P_ID_PEDIDO;
    RETURN V_DIAS;
END;
/

-- 9. Obtener proveedor de producto
CREATE OR REPLACE FUNCTION OBTENER_PROVEEDOR_PRODUCTO(
    P_ID_PRODUCTO NUMBER
) RETURN VARCHAR2 IS
    V_NOMBRE VARCHAR2(50);
BEGIN
    SELECT PR.NOMBRE INTO V_NOMBRE
    FROM PRODUCTO P
    JOIN PROVEEDOR PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR
    WHERE P.ID_PRODUCTO = P_ID_PRODUCTO;
    RETURN V_NOMBRE;
END;
/

-- 10. Calcular monto total por categoría
CREATE OR REPLACE FUNCTION CALCULAR_MONTO_TOTAL_CATEGORIA(
    P_ID_CATEGORIA NUMBER
) RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT SUM(PRECIO * STOCK_ACTUAL) INTO V_TOTAL
    FROM PRODUCTO
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    RETURN V_TOTAL;
END;
/

-- 11. Calcular total por cliente
CREATE OR REPLACE FUNCTION CALCULAR_TOTAL_CLIENTE(
    P_ID_CLIENTE NUMBER
) RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT SUM(TOTAL) INTO V_TOTAL
    FROM PEDIDO
    WHERE ID_CLIENTE = P_ID_CLIENTE;
    RETURN V_TOTAL;
END;
/

-- 12. Calcular utilidad de producto (precio - 30% costo estimado)
CREATE OR REPLACE FUNCTION CALCULAR_UTILIDAD_PRODUCTO(
    P_ID_PRODUCTO NUMBER
) RETURN NUMBER IS
    V_UTILIDAD NUMBER;
    V_PRECIO NUMBER;
BEGIN
    SELECT PRECIO INTO V_PRECIO
    FROM PRODUCTO
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;

    V_UTILIDAD := V_PRECIO - (V_PRECIO * 0.30);
    RETURN V_UTILIDAD;
END;
/
