--Tabla Producto
-- INSERTAR PRODUCTO
CREATE OR REPLACE PROCEDURE INSERTAR_PRODUCTO(
    P_ID_PRODUCTO IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2,
    P_PRECIO IN NUMBER,
    P_STOCK_MINIMO IN NUMBER,
    P_STOCK_ACTUAL IN NUMBER,
    P_ID_CATEGORIA IN NUMBER,
    P_ID_PROVEEDOR IN NUMBER
) AS
BEGIN
    INSERT INTO PRODUCTO VALUES(
        P_ID_PRODUCTO,
        P_NOMBRE,
        P_DESCRIPCION,
        P_PRECIO,
        P_STOCK_MINIMO,
        P_STOCK_ACTUAL,
        P_ID_CATEGORIA,
        P_ID_PROVEEDOR
    );
    COMMIT;
END;
/

-- ACTUALIZAR PRODUCTO
CREATE OR REPLACE PROCEDURE ACTUALIZAR_PRODUCTO(
    P_ID_PRODUCTO IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2,
    P_PRECIO IN NUMBER,
    P_STOCK_MINIMO IN NUMBER,
    P_STOCK_ACTUAL IN NUMBER,
    P_ID_CATEGORIA IN NUMBER,
    P_ID_PROVEEDOR IN NUMBER
) AS
BEGIN
    UPDATE PRODUCTO
    SET 
        NOMBRE = P_NOMBRE,
        DESCRIPCION = P_DESCRIPCION,
        PRECIO = P_PRECIO,
        STOCK_MINIMO = P_STOCK_MINIMO,
        STOCK_ACTUAL = P_STOCK_ACTUAL,
        ID_CATEGORIA = P_ID_CATEGORIA,
        ID_PROVEEDOR = P_ID_PROVEEDOR
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;
    COMMIT;
END;
/

-- ELIMINAR PRODUCTO
CREATE OR REPLACE PROCEDURE ELIMINAR_PRODUCTO(
    P_ID_PRODUCTO IN NUMBER
) AS
BEGIN
    DELETE FROM PRODUCTO WHERE ID_PRODUCTO = P_ID_PRODUCTO;
    COMMIT;
END;
/

-- OBTENER PRODUCTOS
CREATE OR REPLACE FUNCTION OBTENER_PRODUCTOS
RETURN SYS_REFCURSOR
AS
    C_PRODUCTOS SYS_REFCURSOR;
BEGIN
    OPEN C_PRODUCTOS FOR SELECT * FROM PRODUCTO;
    RETURN C_PRODUCTOS;
END;
/

--Tabla Categoria
-- INSERTAR CATEGORIA
CREATE OR REPLACE PROCEDURE INSERTAR_CATEGORIA(
    P_ID_CATEGORIA IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    INSERT INTO CATEGORIA VALUES(P_ID_CATEGORIA, P_NOMBRE, P_DESCRIPCION);
    COMMIT;
END;
/

-- ACTUALIZAR CATEGORIA
CREATE OR REPLACE PROCEDURE ACTUALIZAR_CATEGORIA(
    P_ID_CATEGORIA IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    UPDATE CATEGORIA
    SET NOMBRE = P_NOMBRE, DESCRIPCION = P_DESCRIPCION
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    COMMIT;
END;
/

-- ELIMINAR CATEGORIA
CREATE OR REPLACE PROCEDURE ELIMINAR_CATEGORIA(
    P_ID_CATEGORIA IN NUMBER
) AS
BEGIN
    DELETE FROM CATEGORIA WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    COMMIT;
END;
/

-- OBTENER CATEGORIAS
CREATE OR REPLACE FUNCTION OBTENER_CATEGORIAS
RETURN SYS_REFCURSOR
AS
    C_CATEGORIAS SYS_REFCURSOR;
BEGIN
    OPEN C_CATEGORIAS FOR SELECT * FROM CATEGORIA;
    RETURN C_CATEGORIAS;
END;
/

--Tabla Movimientos
-- INSERTAR MOVIMIENTO
CREATE OR REPLACE PROCEDURE INSERTAR_MOVIMIENTO(
    P_ID_MOVIMIENTO IN NUMBER,
    P_TIPO IN VARCHAR2,
    P_CANTIDAD IN NUMBER,
    P_ID_PRODUCTO IN NUMBER
) AS
BEGIN
    INSERT INTO MOVIMIENTOS VALUES(P_ID_MOVIMIENTO, P_TIPO, P_CANTIDAD, P_ID_PRODUCTO);
    COMMIT;
END;
/

-- ACTUALIZAR MOVIMIENTO
CREATE OR REPLACE PROCEDURE ACTUALIZAR_MOVIMIENTO(
    P_ID_MOVIMIENTO IN NUMBER,
    P_TIPO IN VARCHAR2,
    P_CANTIDAD IN NUMBER,
    P_ID_PRODUCTO IN NUMBER
) AS
BEGIN
    UPDATE MOVIMIENTOS
    SET TIPO = P_TIPO, CANTIDAD = P_CANTIDAD, ID_PRODUCTO = P_ID_PRODUCTO
    WHERE ID_MOVIMIENTO = P_ID_MOVIMIENTO;
    COMMIT;
END;
/

-- ELIMINAR MOVIMIENTO
CREATE OR REPLACE PROCEDURE ELIMINAR_MOVIMIENTO(
    P_ID_MOVIMIENTO IN NUMBER
) AS
BEGIN
    DELETE FROM MOVIMIENTOS WHERE ID_MOVIMIENTO = P_ID_MOVIMIENTO;
    COMMIT;
END;
/

-- OBTENER MOVIMIENTOS
CREATE OR REPLACE FUNCTION OBTENER_MOVIMIENTOS
RETURN SYS_REFCURSOR
AS
    C_MOVIMIENTOS SYS_REFCURSOR;
BEGIN
    OPEN C_MOVIMIENTOS FOR SELECT * FROM MOVIMIENTOS;
    RETURN C_MOVIMIENTOS;
END;
/

--Tabla     Proveedor
-- INSERTAR PROVEEDOR
CREATE OR REPLACE PROCEDURE INSERTAR_PROVEEDOR(
    P_ID_PROVEEDOR IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_TELEFONO IN NUMBER,
    P_EMAIL IN VARCHAR2,
    P_DIRECCION IN VARCHAR2
) AS
BEGIN
    INSERT INTO PROVEEDOR VALUES(P_ID_PROVEEDOR, P_NOMBRE, P_TELEFONO, P_EMAIL, P_DIRECCION);
    COMMIT;
END;
/

-- ACTUALIZAR PROVEEDOR
CREATE OR REPLACE PROCEDURE ACTUALIZAR_PROVEEDOR(
    P_ID_PROVEEDOR IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_TELEFONO IN NUMBER,
    P_EMAIL IN VARCHAR2,
    P_DIRECCION IN VARCHAR2
) AS
BEGIN
    UPDATE PROVEEDOR
    SET 
        NOMBRE = P_NOMBRE,
        TELEFONO = P_TELEFONO,
        EMAIL = P_EMAIL,
        DIRECCION = P_DIRECCION
    WHERE ID_PROVEEDOR = P_ID_PROVEEDOR;
    COMMIT;
END;
/

-- ELIMINAR PROVEEDOR
CREATE OR REPLACE PROCEDURE ELIMINAR_PROVEEDOR(
    P_ID_PROVEEDOR IN NUMBER
) AS
BEGIN
    DELETE FROM PROVEEDOR WHERE ID_PROVEEDOR = P_ID_PROVEEDOR;
    COMMIT;
END;
/